name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest" # Or specify a version like '16' or '18'
          cache: "npm" # Cache node_modules to speed up builds

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI

      - name: Format code
        run: npm run format

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test
